# Generated by Django 3.0.6 on 2020-05-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.TextField(default='likelion'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
