# Generated by Django 3.0.6 on 2020-05-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200520_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='d_day',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.TextField(default='personal'),
        ),
    ]
