# Generated by Django 3.0.6 on 2020-05-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200520_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='d_day',
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
