# Generated by Django 3.0.6 on 2020-05-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200520_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='d_day',
            field=models.TextField(null=True),
        ),
    ]
