# Generated by Django 3.0.6 on 2020-05-16 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 22, 8, 40, 871918)),
        ),
    ]
