# Generated by Django 3.0.8 on 2020-07-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
